favicon: null
name: Jimmy Kryzak
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3456169
  brandStrength: 1
  lightness: 0.234767
  brandColors:
    - '#F1E1C6'
    - '#1F2120'
    - '#C7BD7F'
    - '#6E4B1F'
    - '#916E30'
  rhythmicContrast: 0.781362
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9634550984483212
analytics:
  twitter: null
  google: null
  facebook: null
