name: Jimmy Kryzak
favicon: null
layout_spectrum: 0.9634550984483212
typography_spectrum: 0.6940991070587188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0d0a'
    - '#e8f4f1'
    - '#3b2a22'
    - '#6d4541'
    - '#d0a9a7'
  brandStrength: 0.07158166891895235
  lightness: 0.5289055705070496
  saturation: 0.34561686287634075
  rhythmicContrast: 0.21213383739814162
purpose: []
