favicon: null
name: Jimmy Kryzak
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9193549
  brandStrength: 1
  lightness: 0.4964158
  brandColors:
    - '#101010'
    - '#444248'
    - '#7C6863'
    - '#D3937E'
    - '#E5B7AB'
  rhythmicContrast: 1
typography_spectrum: 1
layout_spectrum: 0.9634550984483212
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
